// Generated by theme:gen from the brief. Do not edit.
import "@fontsource/source-serif-4/400.css";
import "@fontsource/source-serif-4/600.css";
import "@fontsource/public-sans/400.css";
import "@fontsource/public-sans/600.css";
