// Generated by theme:gen from the brief. Do not edit.
export const routes: { id: string; path: string }[] = [
  { id: "story", path: "/" },
  { id: "tracker", path: "/tracker" },
  { id: "case", path: "/case" },
  { id: "denials", path: "/denials" },
  { id: "appeals", path: "/appeals" },
  { id: "architecture", path: "/architecture" },
];
